In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
df = pd.DataFrame({'X': [1, 2, np.nan],
                   'Y': [1, np.nan, np.nan],
                   'Z': [1, 2, 3]})

In [5]:
df

     X    Y  Z
0  1.0  1.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [6]:
df.dropna()

     X    Y  Z
0  1.0  1.0  1

In [7]:
df.dropna(axis=1)

   Z
0  1
1  2
2  3

In [16]:
df.dropna(thresh=2)

     X    Y  Z
0  1.0  1.0  1
1  2.0  NaN  2

In [17]:
df.fillna(value = 'FILL VALUE')

            X           Y  Z
0         1.0         1.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [25]:
df['X'].fillna(value = df['X'].mean())

0    1.0
1    2.0
2    1.5
Name: X, dtype: float64